# Exploring Alpha Vantage API

### Imports- **Run First**

In [1]:
#open file with your API key
with open('Alpha_Vantage_API_key.txt') as file:
    API_key = file.read()
API_key = API_key.strip()

In [2]:
#import libraries
from alpha_vantage.timeseries import TimeSeries

import requests
from bs4 import BeautifulSoup

import pandas as pd
import io

In [3]:
#build TimeSeries variable from Alpha Vantage API
ts1 = TimeSeries(key = API_key)

### How to put stock data into a DataFrame

#### Requests Method

In [17]:
#get weekly stock data of Apple in DataFrame format
url  = url = 'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol=AAPL&apikey=' + str(API_key) + '&datatype=csv'
r = requests.get(url).content
data = pd.read_csv(io.StringIO(r.decode('utf-8')))
print(data)

       timestamp    open    high     low   close     volume
0     2024-07-31  216.96  223.82  215.75  222.08  126946644
1     2024-07-26  227.01  227.78  214.62  217.96  242932215
2     2024-07-19  236.48  237.23  222.27  224.31  278397452
3     2024-07-12  227.09  233.08  223.25  230.54  287640514
4     2024-07-05  212.09  226.45  211.92  226.34  216231316
...          ...     ...     ...     ...     ...        ...
1286  1999-12-10  114.56  118.00   99.00  103.00   25152800
1287  1999-12-03   94.25  115.56   93.25  115.00   28046300
1288  1999-11-26   91.75   95.50   88.50   95.06    9757600
1289  1999-11-19   89.62   94.75   88.06   92.44   13711000
1290  1999-11-12   87.75   97.73   86.75   90.62   25776200

[1291 rows x 6 columns]

In [18]:
#get head of data
data.head()

    timestamp    open    high     low   close     volume
0  2024-07-31  216.96  223.82  215.75  222.08  126946644
1  2024-07-26  227.01  227.78  214.62  217.96  242932215
2  2024-07-19  236.48  237.23  222.27  224.31  278397452
3  2024-07-12  227.09  233.08  223.25  230.54  287640514
4  2024-07-05  212.09  226.45  211.92  226.34  216231316

#### Python Package Method

In [19]:
#store Apple stock intraday data in data and meta_data variables
apple1, metadata = ts1.get_intraday('AAPL')

In [20]:
#print meta_data
metadata

{'1. Information': 'Intraday (15min) open, high, low, close prices and volume',
 '2. Symbol': 'AAPL',
 '3. Last Refreshed': '2024-07-31 19:45:00',
 '4. Interval': '15min',
 '5. Output Size': 'Compact',
 '6. Time Zone': 'US/Eastern'}

In [22]:
#print data
apple1

{'2024-07-31 19:45:00': {'1. open': '223.9000',
  '2. high': '223.9300',
  '3. low': '223.5100',
  '4. close': '223.8000',
  '5. volume': '25023'},
 '2024-07-31 19:30:00': {'1. open': '223.6100',
  '2. high': '223.9440',
  '3. low': '223.5750',
  '4. close': '223.8900',
  '5. volume': '18379'},
 '2024-07-31 19:15:00': {'1. open': '223.2200',
  '2. high': '223.7500',
  '3. low': '223.2200',
  '4. close': '223.6900',
  '5. volume': '28618'},
 '2024-07-31 19:00:00': {'1. open': '223.2900',
  '2. high': '223.4000',
  '3. low': '223.0680',
  '4. close': '223.2900',
  '5. volume': '19380'},
 '2024-07-31 18:45:00': {'1. open': '223.2540',
  '2. high': '223.3300',
  '3. low': '223.0000',
  '4. close': '223.2500',
  '5. volume': '11288'},
 '2024-07-31 18:30:00': {'1. open': '223.0000',
  '2. high': '223.2800',
  '3. low': '222.6100',
  '4. close': '223.1500',
  '5. volume': '15455'},
 '2024-07-31 18:15:00': {'1. open': '223.1000',
  '2. high': '223.1500',
  '3. low': '222.7500',
  '4. close': '222.9000',
  '5. volume': '14922'},
 '2024-07-31 18:00:00': {'1. open': '222.8600',
  '2. high': '223.3000',
  '3. low': '222.0800',
  '4. close': '223.1000',
  '5. volume': '323949'},
 '2024-07-31 17:45:00': {'1. open': '222.7200',
  '2. high': '222.9000',
  '3. low': '222.5600',
  '4. close': '222.9000',
  '5. volume': '20816'},
 '2024-07-31 17:30:00': {'1. open': '222.4800',
  '2. high': '222.8800',
  '3. low': '222.3200',
  '4. close': '222.6550',
  '5. volume': '18042'},
 '2024-07-31 17:15:00': {'1. open': '222.8700',
  '2. high': '222.9000',
  '3. low': '222.3500',
  '4. close': '222.4800',
  '5. volume': '21503'},
 '2024-07-31 17:00:00': {'1. open': '222.4050',
  '2. high': '222.9000',
  '3. low': '222.0800',
  '4. close': '222.9000',
  '5. volume': '63178'},
 '2024-07-31 16:45:00': {'1. open': '222.5600',
  '2. high': '222.8000',
  '3. low': '222.2300',
  '4. close': '222.4100',
  '5. volume': '21190'},
 '2024-07-31 16:30:00': {'1. open': '222.5490',
  '2. high': '222.8800',
  '3. low': '222.0800',
  '4. close': '222.5000',
  '5. volume': '443493'},
 '2024-07-31 16:15:00': {'1. open': '222.2550',
  '2. high': '222.6500',
  '3. low': '222.0800',
  '4. close': '222.5000',
  '5. volume': '43179'},
 '2024-07-31 16:00:00': {'1. open': '221.9900',
  '2. high': '223.4000',
  '3. low': '221.7100',
  '4. close': '222.4300',
  '5. volume': '20612597'},
 '2024-07-31 15:45:00': {'1. open': '222.8400',
  '2. high': '222.9800',
  '3. low': '221.6600',
  '4. close': '221.9900',
  '5. volume': '3952609'},
 '2024-07-31 15:30:00': {'1. open': '221.6400',
  '2. high': '223.0100',
  '3. low': '221.3700',
  '4. close': '222.8600',
  '5. volume': '1666032'},
 '2024-07-31 15:15:00': {'1. open': '222.6000',
  '2. high': '223.0200',
  '3. low': '221.2850',
  '4. close': '221.6100',
  '5. volume': '1839377'},
 '2024-07-31 15:00:00': {'1. open': '222.6650',
  '2. high': '223.0300',
  '3. low': '222.4200',
  '4. close': '222.5900',
  '5. volume': '1177388'},
 '2024-07-31 14:45:00': {'1. open': '223.1700',
  '2. high': '223.3000',
  '3. low': '222.5400',
  '4. close': '222.6650',
  '5. volume': '874571'},
 '2024-07-31 14:30:00': {'1. open': '222.9300',
  '2. high': '223.3700',
  '3. low': '222.3300',
  '4. close': '223.1800',
  '5. volume': '1059742'},
 '2024-07-31 14:15:00': {'1. open': '222.6570',
  '2. high': '223.0100',
  '3. low': '222.6570',
  '4. close': '222.9400',
  '5. volume': '627230'},
 '2024-07-31 14:00:00': {'1. open': '222.1900',
  '2. high': '222.7800',
  '3. low': '221.9200',
  '4. close': '222.6600',
  '5. volume': '994431'},
 '2024-07-31 13:45:00': {'1. open': '221.7400',
  '2. high': '222.4500',
  '3. low': '221.5700',
  '4. close': '222.1700',
  '5. volume': '723849'},
 '2024-07-31 13:30:00': {'1. open': '222.5950',
  '2. high': '222.6000',
  '3. low': '221.3100',
  '4. close': '221.7500',
  '5. volume': '1164108'},
 '2024-07-31 13:15:00': {'1. open': '222.7300',
  '2. high': '223.0100',
  '3. low': '222.5200',
  '4. close': '222.6000',
  '5. volume': '1293729'},
 '2024-07-31 13:00:00': {'1. open': '222.5400',
  '2. high': '222.8800',
  '3. low': '222.4500',
  '4. close': '222.7450',
  '5. volume': '863849'},
 '2024-07-31 12:45:00': {'1. open': '222.2900',
  '2. high': '222.7600',
  '3. low': '222.2600',
  '4. close': '222.5400',
  '5. volume': '762922'},
 '2024-07-31 12:30:00': {'1. open': '222.3840',
  '2. high': '222.3900',
  '3. low': '222.0800',
  '4. close': '222.3000',
  '5. volume': '563641'},
 '2024-07-31 12:15:00': {'1. open': '222.6100',
  '2. high': '222.6270',
  '3. low': '222.1700',
  '4. close': '222.3700',
  '5. volume': '621379'},
 '2024-07-31 12:00:00': {'1. open': '222.5700',
  '2. high': '222.7000',
  '3. low': '222.3500',
  '4. close': '222.6100',
  '5. volume': '675384'},
 '2024-07-31 11:45:00': {'1. open': '222.5800',
  '2. high': '222.7300',
  '3. low': '222.3500',
  '4. close': '222.5500',
  '5. volume': '906228'},
 '2024-07-31 11:30:00': {'1. open': '223.1550',
  '2. high': '223.3700',
  '3. low': '222.4900',
  '4. close': '222.5850',
  '5. volume': '904684'},
 '2024-07-31 11:15:00': {'1. open': '222.5400',
  '2. high': '223.1700',
  '3. low': '222.3100',
  '4. close': '223.1550',
  '5. volume': '933844'},
 '2024-07-31 11:00:00': {'1. open': '222.6050',
  '2. high': '222.7900',
  '3. low': '222.3000',
  '4. close': '222.5350',
  '5. volume': '1083441'},
 '2024-07-31 10:45:00': {'1. open': '223.2600',
  '2. high': '223.8200',
  '3. low': '222.5600',
  '4. close': '222.6100',
  '5. volume': '1570393'},
 '2024-07-31 10:30:00': {'1. open': '222.8400',
  '2. high': '223.8200',
  '3. low': '222.6500',
  '4. close': '223.2600',
  '5. volume': '1560168'},
 '2024-07-31 10:15:00': {'1. open': '222.3400',
  '2. high': '223.4400',
  '3. low': '222.2500',
  '4. close': '222.8300',
  '5. volume': '2150312'},
 '2024-07-31 10:00:00': {'1. open': '221.9800',
  '2. high': '222.6300',
  '3. low': '221.8300',
  '4. close': '222.3400',
  '5. volume': '1561352'},
 '2024-07-31 09:45:00': {'1. open': '221.6300',
  '2. high': '222.5600',
  '3. low': '221.3900',
  '4. close': '221.9800',
  '5. volume': '1823442'},
 '2024-07-31 09:30:00': {'1. open': '221.4400',
  '2. high': '222.6600',
  '3. low': '220.6300',
  '4. close': '221.6200',
  '5. volume': '4301486'},
 '2024-07-31 09:15:00': {'1. open': '221.5700',
  '2. high': '221.8200',
  '3. low': '220.6000',
  '4. close': '221.5500',
  '5. volume': '155181'},
 '2024-07-31 09:00:00': {'1. open': '221.2300',
  '2. high': '221.9300',
  '3. low': '221.1400',
  '4. close': '221.5700',
  '5. volume': '109698'},
 '2024-07-31 08:45:00': {'1. open': '220.4500',
  '2. high': '221.3300',
  '3. low': '218.8000',
  '4. close': '221.2300',
  '5. volume': '142674'},
 '2024-07-31 08:30:00': {'1. open': '219.9700',
  '2. high': '220.6500',
  '3. low': '219.8400',
  '4. close': '220.5700',
  '5. volume': '73679'},
 '2024-07-31 08:15:00': {'1. open': '219.9800',
  '2. high': '228.2590',
  '3. low': '219.8300',
  '4. close': '219.9900',
  '5. volume': '49541'},
 '2024-07-31 08:00:00': {'1. open': '220.0000',
  '2. high': '220.7050',
  '3. low': '218.7000',
  '4. close': '219.9700',
  '5. volume': '110996'},
 '2024-07-31 07:45:00': {'1. open': '220.2200',
  '2. high': '220.3700',
  '3. low': '220.1200',
  '4. close': '220.2500',
  '5. volume': '31884'},
 '2024-07-31 07:30:00': {'1. open': '220.1800',
  '2. high': '220.3100',
  '3. low': '220.1100',
  '4. close': '220.2400',
  '5. volume': '31574'},
 '2024-07-31 07:15:00': {'1. open': '220.5500',
  '2. high': '220.6000',
  '3. low': '220.0100',
  '4. close': '220.2100',
  '5. volume': '20851'},
 '2024-07-31 07:00:00': {'1. open': '220.3500',
  '2. high': '220.5900',
  '3. low': '220.0100',
  '4. close': '220.5500',
  '5. volume': '30385'},
 '2024-07-31 06:45:00': {'1. open': '220.0500',
  '2. high': '220.4600',
  '3. low': '220.0200',
  '4. close': '220.4200',
  '5. volume': '11988'},
 '2024-07-31 06:30:00': {'1. open': '220.0000',
  '2. high': '220.1000',
  '3. low': '219.9100',
  '4. close': '220.0700',
  '5. volume': '4119'},
 '2024-07-31 06:15:00': {'1. open': '220.2400',
  '2. high': '220.3500',
  '3. low': '219.9700',
  '4. close': '220.0000',
  '5. volume': '5057'},
 '2024-07-31 06:00:00': {'1. open': '220.3000',
  '2. high': '220.3600',
  '3. low': '220.1200',
  '4. close': '220.2800',
  '5. volume': '5110'},
 '2024-07-31 05:45:00': {'1. open': '220.3000',
  '2. high': '220.5200',
  '3. low': '220.1600',
  '4. close': '220.2800',
  '5. volume': '3652'},
 '2024-07-31 05:30:00': {'1. open': '220.2200',
  '2. high': '220.7000',
  '3. low': '220.1300',
  '4. close': '220.3200',
  '5. volume': '11161'},
 '2024-07-31 05:15:00': {'1. open': '220.1000',
  '2. high': '220.3200',
  '3. low': '220.0600',
  '4. close': '220.2400',
  '5. volume': '3600'},
 '2024-07-31 05:00:00': {'1. open': '220.3200',
  '2. high': '220.5000',
  '3. low': '220.0000',
  '4. close': '220.1200',
  '5. volume': '11887'},
 '2024-07-31 04:45:00': {'1. open': '219.8900',
  '2. high': '220.3500',
  '3. low': '219.8000',
  '4. close': '220.1900',
  '5. volume': '8946'},
 '2024-07-31 04:30:00': {'1. open': '219.7300',
  '2. high': '220.0000',
  '3. low': '219.7200',
  '4. close': '219.9000',
  '5. volume': '6008'},
 '2024-07-31 04:15:00': {'1. open': '219.8500',
  '2. high': '220.0000',
  '3. low': '219.6300',
  '4. close': '219.6900',
  '5. volume': '10672'},
 '2024-07-31 04:00:00': {'1. open': '219.6700',
  '2. high': '219.9100',
  '3. low': '219.1500',
  '4. close': '219.8400',
  '5. volume': '30760'},
 '2024-07-30 19:45:00': {'1. open': '217.9600',
  '2. high': '218.4800',
  '3. low': '217.8000',
  '4. close': '218.1600',
  '5. volume': '19844'},
 '2024-07-30 19:30:00': {'1. open': '217.9250',
  '2. high': '218.0000',
  '3. low': '217.5100',
  '4. close': '217.8750',
  '5. volume': '12048'},
 '2024-07-30 19:15:00': {'1. open': '217.6400',
  '2. high': '218.2000',
  '3. low': '217.5000',
  '4. close': '217.9500',
  '5. volume': '18848'},
 '2024-07-30 19:00:00': {'1. open': '217.6250',
  '2. high': '217.6900',
  '3. low': '217.3500',
  '4. close': '217.6900',
  '5. volume': '7011'},
 '2024-07-30 18:45:00': {'1. open': '217.5500',
  '2. high': '217.7800',
  '3. low': '217.3100',
  '4. close': '217.5500',
  '5. volume': '9043'},
 '2024-07-30 18:30:00': {'1. open': '218.0800',
  '2. high': '218.2000',
  '3. low': '217.0500',
  '4. close': '217.4300',
  '5. volume': '26276'},
 '2024-07-30 18:15:00': {'1. open': '217.4900',
  '2. high': '218.1400',
  '3. low': '217.3300',
  '4. close': '218.1400',
  '5. volume': '32204'},
 '2024-07-30 18:00:00': {'1. open': '217.0500',
  '2. high': '218.2000',
  '3. low': '217.0100',
  '4. close': '217.3100',
  '5. volume': '42075'},
 '2024-07-30 17:45:00': {'1. open': '216.9400',
  '2. high': '219.8500',
  '3. low': '216.8600',
  '4. close': '217.1500',
  '5. volume': '18001'},
 '2024-07-30 17:30:00': {'1. open': '216.7500',
  '2. high': '218.8000',
  '3. low': '216.6500',
  '4. close': '216.9300',
  '5. volume': '35233'},
 '2024-07-30 17:15:00': {'1. open': '217.1000',
  '2. high': '217.2500',
  '3. low': '216.6600',
  '4. close': '216.7500',
  '5. volume': '24926'},
 '2024-07-30 17:00:00': {'1. open': '217.4500',
  '2. high': '217.5500',
  '3. low': '210.9500',
  '4. close': '217.1300',
  '5. volume': '604981'},
 '2024-07-30 16:45:00': {'1. open': '217.2300',
  '2. high': '219.5280',
  '3. low': '193.5450',
  '4. close': '217.4500',
  '5. volume': '613098'},
 '2024-07-30 16:30:00': {'1. open': '218.0600',
  '2. high': '218.8000',
  '3. low': '217.0300',
  '4. close': '217.2300',
  '5. volume': '121801'},
 '2024-07-30 16:15:00': {'1. open': '217.9000',
  '2. high': '218.8000',
  '3. low': '217.5000',
  '4. close': '217.8600',
  '5. volume': '102553'},
 '2024-07-30 16:00:00': {'1. open': '218.7900',
  '2. high': '218.8000',
  '3. low': '169.3000',
  '4. close': '217.9500',
  '5. volume': '13265816'},
 '2024-07-30 15:45:00': {'1. open': '219.0000',
  '2. high': '219.9200',
  '3. low': '218.6200',
  '4. close': '218.7900',
  '5. volume': '4129783'},
 '2024-07-30 15:30:00': {'1. open': '218.6400',
  '2. high': '219.0000',
  '3. low': '218.4500',
  '4. close': '218.9900',
  '5. volume': '1536918'},
 '2024-07-30 15:15:00': {'1. open': '218.1100',
  '2. high': '218.7100',
  '3. low': '218.1100',
  '4. close': '218.6300',
  '5. volume': '934284'},
 '2024-07-30 15:00:00': {'1. open': '218.2100',
  '2. high': '218.3700',
  '3. low': '217.9750',
  '4. close': '218.1200',
  '5. volume': '754266'},
 '2024-07-30 14:45:00': {'1. open': '218.2500',
  '2. high': '218.3900',
  '3. low': '217.9700',
  '4. close': '218.2000',
  '5. volume': '788664'},
 '2024-07-30 14:30:00': {'1. open': '218.2800',
  '2. high': '218.4650',
  '3. low': '218.1000',
  '4. close': '218.2450',
  '5. volume': '551168'},
 '2024-07-30 14:15:00': {'1. open': '218.1300',
  '2. high': '218.7400',
  '3. low': '218.1300',
  '4. close': '218.2850',
  '5. volume': '1015801'},
 '2024-07-30 14:00:00': {'1. open': '217.5850',
  '2. high': '218.2000',
  '3. low': '217.5800',
  '4. close': '218.1200',
  '5. volume': '1014554'},
 '2024-07-30 13:45:00': {'1. open': '217.4000',
  '2. high': '217.6200',
  '3. low': '217.2200',
  '4. close': '217.5800',
  '5. volume': '612720'},
 '2024-07-30 13:30:00': {'1. open': '217.2500',
  '2. high': '217.4100',
  '3. low': '216.9600',
  '4. close': '217.4000',
  '5. volume': '653296'},
 '2024-07-30 13:15:00': {'1. open': '217.1100',
  '2. high': '217.3500',
  '3. low': '216.9100',
  '4. close': '217.2500',
  '5. volume': '671613'},
 '2024-07-30 13:00:00': {'1. open': '216.1700',
  '2. high': '217.2100',
  '3. low': '216.1200',
  '4. close': '217.1200',
  '5. volume': '968034'},
 '2024-07-30 12:45:00': {'1. open': '217.1200',
  '2. high': '217.1700',
  '3. low': '216.1500',
  '4. close': '216.1500',
  '5. volume': '960888'},
 '2024-07-30 12:30:00': {'1. open': '216.9600',
  '2. high': '217.2100',
  '3. low': '216.7300',
  '4. close': '217.1400',
  '5. volume': '614841'},
 '2024-07-30 12:15:00': {'1. open': '217.1300',
  '2. high': '217.2150',
  '3. low': '216.6000',
  '4. close': '216.9800',
  '5. volume': '658058'},
 '2024-07-30 12:00:00': {'1. open': '216.5530',
  '2. high': '217.1600',
  '3. low': '216.5500',
  '4. close': '217.1400',
  '5. volume': '739269'},
 '2024-07-30 11:45:00': {'1. open': '216.5100',
  '2. high': '216.7500',
  '3. low': '216.5000',
  '4. close': '216.5450',
  '5. volume': '756707'},
 '2024-07-30 11:30:00': {'1. open': '217.2800',
  '2. high': '217.5400',
  '3. low': '216.3300',
  '4. close': '216.5200',
  '5. volume': '1383230'},
 '2024-07-30 11:15:00': {'1. open': '217.3600',
  '2. high': '217.5800',
  '3. low': '217.1600',
  '4. close': '217.2900',
  '5. volume': '1125540'},
 '2024-07-30 11:00:00': {'1. open': '218.7290',
  '2. high': '218.8200',
  '3. low': '217.3300',
  '4. close': '217.3800',
  '5. volume': '1906510'}}

In [23]:
#store data into a DataFrame
apple1

{'2024-07-31 19:45:00': {'1. open': '223.9000',
  '2. high': '223.9300',
  '3. low': '223.5100',
  '4. close': '223.8000',
  '5. volume': '25023'},
 '2024-07-31 19:30:00': {'1. open': '223.6100',
  '2. high': '223.9440',
  '3. low': '223.5750',
  '4. close': '223.8900',
  '5. volume': '18379'},
 '2024-07-31 19:15:00': {'1. open': '223.2200',
  '2. high': '223.7500',
  '3. low': '223.2200',
  '4. close': '223.6900',
  '5. volume': '28618'},
 '2024-07-31 19:00:00': {'1. open': '223.2900',
  '2. high': '223.4000',
  '3. low': '223.0680',
  '4. close': '223.2900',
  '5. volume': '19380'},
 '2024-07-31 18:45:00': {'1. open': '223.2540',
  '2. high': '223.3300',
  '3. low': '223.0000',
  '4. close': '223.2500',
  '5. volume': '11288'},
 '2024-07-31 18:30:00': {'1. open': '223.0000',
  '2. high': '223.2800',
  '3. low': '222.6100',
  '4. close': '223.1500',
  '5. volume': '15455'},
 '2024-07-31 18:15:00': {'1. open': '223.1000',
  '2. high': '223.1500',
  '3. low': '222.7500',
  '4. close': '222.9000',
  '5. volume': '14922'},
 '2024-07-31 18:00:00': {'1. open': '222.8600',
  '2. high': '223.3000',
  '3. low': '222.0800',
  '4. close': '223.1000',
  '5. volume': '323949'},
 '2024-07-31 17:45:00': {'1. open': '222.7200',
  '2. high': '222.9000',
  '3. low': '222.5600',
  '4. close': '222.9000',
  '5. volume': '20816'},
 '2024-07-31 17:30:00': {'1. open': '222.4800',
  '2. high': '222.8800',
  '3. low': '222.3200',
  '4. close': '222.6550',
  '5. volume': '18042'},
 '2024-07-31 17:15:00': {'1. open': '222.8700',
  '2. high': '222.9000',
  '3. low': '222.3500',
  '4. close': '222.4800',
  '5. volume': '21503'},
 '2024-07-31 17:00:00': {'1. open': '222.4050',
  '2. high': '222.9000',
  '3. low': '222.0800',
  '4. close': '222.9000',
  '5. volume': '63178'},
 '2024-07-31 16:45:00': {'1. open': '222.5600',
  '2. high': '222.8000',
  '3. low': '222.2300',
  '4. close': '222.4100',
  '5. volume': '21190'},
 '2024-07-31 16:30:00': {'1. open': '222.5490',
  '2. high': '222.8800',
  '3. low': '222.0800',
  '4. close': '222.5000',
  '5. volume': '443493'},
 '2024-07-31 16:15:00': {'1. open': '222.2550',
  '2. high': '222.6500',
  '3. low': '222.0800',
  '4. close': '222.5000',
  '5. volume': '43179'},
 '2024-07-31 16:00:00': {'1. open': '221.9900',
  '2. high': '223.4000',
  '3. low': '221.7100',
  '4. close': '222.4300',
  '5. volume': '20612597'},
 '2024-07-31 15:45:00': {'1. open': '222.8400',
  '2. high': '222.9800',
  '3. low': '221.6600',
  '4. close': '221.9900',
  '5. volume': '3952609'},
 '2024-07-31 15:30:00': {'1. open': '221.6400',
  '2. high': '223.0100',
  '3. low': '221.3700',
  '4. close': '222.8600',
  '5. volume': '1666032'},
 '2024-07-31 15:15:00': {'1. open': '222.6000',
  '2. high': '223.0200',
  '3. low': '221.2850',
  '4. close': '221.6100',
  '5. volume': '1839377'},
 '2024-07-31 15:00:00': {'1. open': '222.6650',
  '2. high': '223.0300',
  '3. low': '222.4200',
  '4. close': '222.5900',
  '5. volume': '1177388'},
 '2024-07-31 14:45:00': {'1. open': '223.1700',
  '2. high': '223.3000',
  '3. low': '222.5400',
  '4. close': '222.6650',
  '5. volume': '874571'},
 '2024-07-31 14:30:00': {'1. open': '222.9300',
  '2. high': '223.3700',
  '3. low': '222.3300',
  '4. close': '223.1800',
  '5. volume': '1059742'},
 '2024-07-31 14:15:00': {'1. open': '222.6570',
  '2. high': '223.0100',
  '3. low': '222.6570',
  '4. close': '222.9400',
  '5. volume': '627230'},
 '2024-07-31 14:00:00': {'1. open': '222.1900',
  '2. high': '222.7800',
  '3. low': '221.9200',
  '4. close': '222.6600',
  '5. volume': '994431'},
 '2024-07-31 13:45:00': {'1. open': '221.7400',
  '2. high': '222.4500',
  '3. low': '221.5700',
  '4. close': '222.1700',
  '5. volume': '723849'},
 '2024-07-31 13:30:00': {'1. open': '222.5950',
  '2. high': '222.6000',
  '3. low': '221.3100',
  '4. close': '221.7500',
  '5. volume': '1164108'},
 '2024-07-31 13:15:00': {'1. open': '222.7300',
  '2. high': '223.0100',
  '3. low': '222.5200',
  '4. close': '222.6000',
  '5. volume': '1293729'},
 '2024-07-31 13:00:00': {'1. open': '222.5400',
  '2. high': '222.8800',
  '3. low': '222.4500',
  '4. close': '222.7450',
  '5. volume': '863849'},
 '2024-07-31 12:45:00': {'1. open': '222.2900',
  '2. high': '222.7600',
  '3. low': '222.2600',
  '4. close': '222.5400',
  '5. volume': '762922'},
 '2024-07-31 12:30:00': {'1. open': '222.3840',
  '2. high': '222.3900',
  '3. low': '222.0800',
  '4. close': '222.3000',
  '5. volume': '563641'},
 '2024-07-31 12:15:00': {'1. open': '222.6100',
  '2. high': '222.6270',
  '3. low': '222.1700',
  '4. close': '222.3700',
  '5. volume': '621379'},
 '2024-07-31 12:00:00': {'1. open': '222.5700',
  '2. high': '222.7000',
  '3. low': '222.3500',
  '4. close': '222.6100',
  '5. volume': '675384'},
 '2024-07-31 11:45:00': {'1. open': '222.5800',
  '2. high': '222.7300',
  '3. low': '222.3500',
  '4. close': '222.5500',
  '5. volume': '906228'},
 '2024-07-31 11:30:00': {'1. open': '223.1550',
  '2. high': '223.3700',
  '3. low': '222.4900',
  '4. close': '222.5850',
  '5. volume': '904684'},
 '2024-07-31 11:15:00': {'1. open': '222.5400',
  '2. high': '223.1700',
  '3. low': '222.3100',
  '4. close': '223.1550',
  '5. volume': '933844'},
 '2024-07-31 11:00:00': {'1. open': '222.6050',
  '2. high': '222.7900',
  '3. low': '222.3000',
  '4. close': '222.5350',
  '5. volume': '1083441'},
 '2024-07-31 10:45:00': {'1. open': '223.2600',
  '2. high': '223.8200',
  '3. low': '222.5600',
  '4. close': '222.6100',
  '5. volume': '1570393'},
 '2024-07-31 10:30:00': {'1. open': '222.8400',
  '2. high': '223.8200',
  '3. low': '222.6500',
  '4. close': '223.2600',
  '5. volume': '1560168'},
 '2024-07-31 10:15:00': {'1. open': '222.3400',
  '2. high': '223.4400',
  '3. low': '222.2500',
  '4. close': '222.8300',
  '5. volume': '2150312'},
 '2024-07-31 10:00:00': {'1. open': '221.9800',
  '2. high': '222.6300',
  '3. low': '221.8300',
  '4. close': '222.3400',
  '5. volume': '1561352'},
 '2024-07-31 09:45:00': {'1. open': '221.6300',
  '2. high': '222.5600',
  '3. low': '221.3900',
  '4. close': '221.9800',
  '5. volume': '1823442'},
 '2024-07-31 09:30:00': {'1. open': '221.4400',
  '2. high': '222.6600',
  '3. low': '220.6300',
  '4. close': '221.6200',
  '5. volume': '4301486'},
 '2024-07-31 09:15:00': {'1. open': '221.5700',
  '2. high': '221.8200',
  '3. low': '220.6000',
  '4. close': '221.5500',
  '5. volume': '155181'},
 '2024-07-31 09:00:00': {'1. open': '221.2300',
  '2. high': '221.9300',
  '3. low': '221.1400',
  '4. close': '221.5700',
  '5. volume': '109698'},
 '2024-07-31 08:45:00': {'1. open': '220.4500',
  '2. high': '221.3300',
  '3. low': '218.8000',
  '4. close': '221.2300',
  '5. volume': '142674'},
 '2024-07-31 08:30:00': {'1. open': '219.9700',
  '2. high': '220.6500',
  '3. low': '219.8400',
  '4. close': '220.5700',
  '5. volume': '73679'},
 '2024-07-31 08:15:00': {'1. open': '219.9800',
  '2. high': '228.2590',
  '3. low': '219.8300',
  '4. close': '219.9900',
  '5. volume': '49541'},
 '2024-07-31 08:00:00': {'1. open': '220.0000',
  '2. high': '220.7050',
  '3. low': '218.7000',
  '4. close': '219.9700',
  '5. volume': '110996'},
 '2024-07-31 07:45:00': {'1. open': '220.2200',
  '2. high': '220.3700',
  '3. low': '220.1200',
  '4. close': '220.2500',
  '5. volume': '31884'},
 '2024-07-31 07:30:00': {'1. open': '220.1800',
  '2. high': '220.3100',
  '3. low': '220.1100',
  '4. close': '220.2400',
  '5. volume': '31574'},
 '2024-07-31 07:15:00': {'1. open': '220.5500',
  '2. high': '220.6000',
  '3. low': '220.0100',
  '4. close': '220.2100',
  '5. volume': '20851'},
 '2024-07-31 07:00:00': {'1. open': '220.3500',
  '2. high': '220.5900',
  '3. low': '220.0100',
  '4. close': '220.5500',
  '5. volume': '30385'},
 '2024-07-31 06:45:00': {'1. open': '220.0500',
  '2. high': '220.4600',
  '3. low': '220.0200',
  '4. close': '220.4200',
  '5. volume': '11988'},
 '2024-07-31 06:30:00': {'1. open': '220.0000',
  '2. high': '220.1000',
  '3. low': '219.9100',
  '4. close': '220.0700',
  '5. volume': '4119'},
 '2024-07-31 06:15:00': {'1. open': '220.2400',
  '2. high': '220.3500',
  '3. low': '219.9700',
  '4. close': '220.0000',
  '5. volume': '5057'},
 '2024-07-31 06:00:00': {'1. open': '220.3000',
  '2. high': '220.3600',
  '3. low': '220.1200',
  '4. close': '220.2800',
  '5. volume': '5110'},
 '2024-07-31 05:45:00': {'1. open': '220.3000',
  '2. high': '220.5200',
  '3. low': '220.1600',
  '4. close': '220.2800',
  '5. volume': '3652'},
 '2024-07-31 05:30:00': {'1. open': '220.2200',
  '2. high': '220.7000',
  '3. low': '220.1300',
  '4. close': '220.3200',
  '5. volume': '11161'},
 '2024-07-31 05:15:00': {'1. open': '220.1000',
  '2. high': '220.3200',
  '3. low': '220.0600',
  '4. close': '220.2400',
  '5. volume': '3600'},
 '2024-07-31 05:00:00': {'1. open': '220.3200',
  '2. high': '220.5000',
  '3. low': '220.0000',
  '4. close': '220.1200',
  '5. volume': '11887'},
 '2024-07-31 04:45:00': {'1. open': '219.8900',
  '2. high': '220.3500',
  '3. low': '219.8000',
  '4. close': '220.1900',
  '5. volume': '8946'},
 '2024-07-31 04:30:00': {'1. open': '219.7300',
  '2. high': '220.0000',
  '3. low': '219.7200',
  '4. close': '219.9000',
  '5. volume': '6008'},
 '2024-07-31 04:15:00': {'1. open': '219.8500',
  '2. high': '220.0000',
  '3. low': '219.6300',
  '4. close': '219.6900',
  '5. volume': '10672'},
 '2024-07-31 04:00:00': {'1. open': '219.6700',
  '2. high': '219.9100',
  '3. low': '219.1500',
  '4. close': '219.8400',
  '5. volume': '30760'},
 '2024-07-30 19:45:00': {'1. open': '217.9600',
  '2. high': '218.4800',
  '3. low': '217.8000',
  '4. close': '218.1600',
  '5. volume': '19844'},
 '2024-07-30 19:30:00': {'1. open': '217.9250',
  '2. high': '218.0000',
  '3. low': '217.5100',
  '4. close': '217.8750',
  '5. volume': '12048'},
 '2024-07-30 19:15:00': {'1. open': '217.6400',
  '2. high': '218.2000',
  '3. low': '217.5000',
  '4. close': '217.9500',
  '5. volume': '18848'},
 '2024-07-30 19:00:00': {'1. open': '217.6250',
  '2. high': '217.6900',
  '3. low': '217.3500',
  '4. close': '217.6900',
  '5. volume': '7011'},
 '2024-07-30 18:45:00': {'1. open': '217.5500',
  '2. high': '217.7800',
  '3. low': '217.3100',
  '4. close': '217.5500',
  '5. volume': '9043'},
 '2024-07-30 18:30:00': {'1. open': '218.0800',
  '2. high': '218.2000',
  '3. low': '217.0500',
  '4. close': '217.4300',
  '5. volume': '26276'},
 '2024-07-30 18:15:00': {'1. open': '217.4900',
  '2. high': '218.1400',
  '3. low': '217.3300',
  '4. close': '218.1400',
  '5. volume': '32204'},
 '2024-07-30 18:00:00': {'1. open': '217.0500',
  '2. high': '218.2000',
  '3. low': '217.0100',
  '4. close': '217.3100',
  '5. volume': '42075'},
 '2024-07-30 17:45:00': {'1. open': '216.9400',
  '2. high': '219.8500',
  '3. low': '216.8600',
  '4. close': '217.1500',
  '5. volume': '18001'},
 '2024-07-30 17:30:00': {'1. open': '216.7500',
  '2. high': '218.8000',
  '3. low': '216.6500',
  '4. close': '216.9300',
  '5. volume': '35233'},
 '2024-07-30 17:15:00': {'1. open': '217.1000',
  '2. high': '217.2500',
  '3. low': '216.6600',
  '4. close': '216.7500',
  '5. volume': '24926'},
 '2024-07-30 17:00:00': {'1. open': '217.4500',
  '2. high': '217.5500',
  '3. low': '210.9500',
  '4. close': '217.1300',
  '5. volume': '604981'},
 '2024-07-30 16:45:00': {'1. open': '217.2300',
  '2. high': '219.5280',
  '3. low': '193.5450',
  '4. close': '217.4500',
  '5. volume': '613098'},
 '2024-07-30 16:30:00': {'1. open': '218.0600',
  '2. high': '218.8000',
  '3. low': '217.0300',
  '4. close': '217.2300',
  '5. volume': '121801'},
 '2024-07-30 16:15:00': {'1. open': '217.9000',
  '2. high': '218.8000',
  '3. low': '217.5000',
  '4. close': '217.8600',
  '5. volume': '102553'},
 '2024-07-30 16:00:00': {'1. open': '218.7900',
  '2. high': '218.8000',
  '3. low': '169.3000',
  '4. close': '217.9500',
  '5. volume': '13265816'},
 '2024-07-30 15:45:00': {'1. open': '219.0000',
  '2. high': '219.9200',
  '3. low': '218.6200',
  '4. close': '218.7900',
  '5. volume': '4129783'},
 '2024-07-30 15:30:00': {'1. open': '218.6400',
  '2. high': '219.0000',
  '3. low': '218.4500',
  '4. close': '218.9900',
  '5. volume': '1536918'},
 '2024-07-30 15:15:00': {'1. open': '218.1100',
  '2. high': '218.7100',
  '3. low': '218.1100',
  '4. close': '218.6300',
  '5. volume': '934284'},
 '2024-07-30 15:00:00': {'1. open': '218.2100',
  '2. high': '218.3700',
  '3. low': '217.9750',
  '4. close': '218.1200',
  '5. volume': '754266'},
 '2024-07-30 14:45:00': {'1. open': '218.2500',
  '2. high': '218.3900',
  '3. low': '217.9700',
  '4. close': '218.2000',
  '5. volume': '788664'},
 '2024-07-30 14:30:00': {'1. open': '218.2800',
  '2. high': '218.4650',
  '3. low': '218.1000',
  '4. close': '218.2450',
  '5. volume': '551168'},
 '2024-07-30 14:15:00': {'1. open': '218.1300',
  '2. high': '218.7400',
  '3. low': '218.1300',
  '4. close': '218.2850',
  '5. volume': '1015801'},
 '2024-07-30 14:00:00': {'1. open': '217.5850',
  '2. high': '218.2000',
  '3. low': '217.5800',
  '4. close': '218.1200',
  '5. volume': '1014554'},
 '2024-07-30 13:45:00': {'1. open': '217.4000',
  '2. high': '217.6200',
  '3. low': '217.2200',
  '4. close': '217.5800',
  '5. volume': '612720'},
 '2024-07-30 13:30:00': {'1. open': '217.2500',
  '2. high': '217.4100',
  '3. low': '216.9600',
  '4. close': '217.4000',
  '5. volume': '653296'},
 '2024-07-30 13:15:00': {'1. open': '217.1100',
  '2. high': '217.3500',
  '3. low': '216.9100',
  '4. close': '217.2500',
  '5. volume': '671613'},
 '2024-07-30 13:00:00': {'1. open': '216.1700',
  '2. high': '217.2100',
  '3. low': '216.1200',
  '4. close': '217.1200',
  '5. volume': '968034'},
 '2024-07-30 12:45:00': {'1. open': '217.1200',
  '2. high': '217.1700',
  '3. low': '216.1500',
  '4. close': '216.1500',
  '5. volume': '960888'},
 '2024-07-30 12:30:00': {'1. open': '216.9600',
  '2. high': '217.2100',
  '3. low': '216.7300',
  '4. close': '217.1400',
  '5. volume': '614841'},
 '2024-07-30 12:15:00': {'1. open': '217.1300',
  '2. high': '217.2150',
  '3. low': '216.6000',
  '4. close': '216.9800',
  '5. volume': '658058'},
 '2024-07-30 12:00:00': {'1. open': '216.5530',
  '2. high': '217.1600',
  '3. low': '216.5500',
  '4. close': '217.1400',
  '5. volume': '739269'},
 '2024-07-30 11:45:00': {'1. open': '216.5100',
  '2. high': '216.7500',
  '3. low': '216.5000',
  '4. close': '216.5450',
  '5. volume': '756707'},
 '2024-07-30 11:30:00': {'1. open': '217.2800',
  '2. high': '217.5400',
  '3. low': '216.3300',
  '4. close': '216.5200',
  '5. volume': '1383230'},
 '2024-07-30 11:15:00': {'1. open': '217.3600',
  '2. high': '217.5800',
  '3. low': '217.1600',
  '4. close': '217.2900',
  '5. volume': '1125540'},
 '2024-07-30 11:00:00': {'1. open': '218.7290',
  '2. high': '218.8200',
  '3. low': '217.3300',
  '4. close': '217.3800',
  '5. volume': '1906510'}}

In [24]:
#Bring in data in DataFrame format
#second method to do the same
df_apple1 = pd.DataFrame(apple1).transpose().reset_index()
df_apple1.head()

                 index   1. open   2. high    3. low  4. close 5. volume
0  2024-07-31 19:45:00  223.9000  223.9300  223.5100  223.8000     25023
1  2024-07-31 19:30:00  223.6100  223.9440  223.5750  223.8900     18379
2  2024-07-31 19:15:00  223.2200  223.7500  223.2200  223.6900     28618
3  2024-07-31 19:00:00  223.2900  223.4000  223.0680  223.2900     19380
4  2024-07-31 18:45:00  223.2540  223.3300  223.0000  223.2500     11288

In [25]:
# display new intraday stock data
#second method to obtain in adatframe
ts2 = TimeSeries(key=API_key, output_format='pandas')

In [30]:
#get full amount of intraday stock data for data and meta_data
apple2, metadata = ts2.get_intraday('AAPL')

In [28]:
#print meta_data
metadata

{'1. Information': 'Intraday (15min) open, high, low, close prices and volume',
 '2. Symbol': 'AAPL',
 '3. Last Refreshed': '2024-07-31 19:45:00',
 '4. Interval': '15min',
 '5. Output Size': 'Compact',
 '6. Time Zone': 'US/Eastern'}

In [31]:
#print data with reset index
apple2.reset_index()

                  date  1. open  2. high   3. low  4. close  5. volume
0  2024-07-31 19:45:00  223.900  223.930  223.510   223.800    25023.0
1  2024-07-31 19:30:00  223.610  223.944  223.575   223.890    18379.0
2  2024-07-31 19:15:00  223.220  223.750  223.220   223.690    28618.0
3  2024-07-31 19:00:00  223.290  223.400  223.068   223.290    19380.0
4  2024-07-31 18:45:00  223.254  223.330  223.000   223.250    11288.0
..                 ...      ...      ...      ...       ...        ...
95 2024-07-30 12:00:00  216.553  217.160  216.550   217.140   739269.0
96 2024-07-30 11:45:00  216.510  216.750  216.500   216.545   756707.0
97 2024-07-30 11:30:00  217.280  217.540  216.330   216.520  1383230.0
98 2024-07-30 11:15:00  217.360  217.580  217.160   217.290  1125540.0
99 2024-07-30 11:00:00  218.729  218.820  217.330   217.380  1906510.0

[100 rows x 6 columns]